# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4e0c5ef1361f5e23710736cb3362e8baf9e16040a88ca313e9bd92e029d2184399dcf33b36b0dd225afe03d89a5829dee8fa5d4a37d9409c4844cff5c668c50

test:
  secret_key_base: 30dc16c91dbfd23e5ae832eb39018fb73b10d39f7c25b0867d6fb1d66dea290327807d6efe6e43dfe441edf1de6fd9d7cff530f186a099beea2253adfe534e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
